[package]
name = "io-smtp"
description = "SMTP client library"
version = "0.0.1"
authors = ["soywod <pimalaya.org@posteo.net>"]
edition = "2024"
rust-version = "1.87"
license = "MIT OR Apache-2.0"
categories = ["email", "no-std"]
keywords = ["email", "smtp", "client", "std", "io-free"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-smtp/latest/io_smtp"
repository = "https://github.com/pimalaya/io-smtp"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client"]
client = []
scram = ["dep:hmac", "dep:pbkdf2", "dep:rand", "dep:sha2"]
rustls-ring = ["client", "pimalaya-stream/rustls-ring", "dep:anyhow", "dep:url"]
rustls-aws  = ["client", "pimalaya-stream/rustls-aws", "dep:anyhow", "dep:url"]
native-tls  = ["client", "pimalaya-stream/native-tls", "dep:anyhow", "dep:url"]
vendored = ["pimalaya-stream?/vendored"]

[dev-dependencies]
env_logger = "0.11"

[dependencies]
anyhow = { version = "1", optional = true }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
bounded-static = { version = "0.8", default-features = false, features = ["alloc"] }
bounded-static-derive = { version = "0.8", default-features = false }
chumsky = { version = "0.13", default-features = false }
hmac = { version = "0.13", optional = true, default-features = false }
log = { version = "0.4", default-features = false }
pbkdf2 = { version = "0.13.0-rc.10", optional = true, default-features = false, features = ["hmac"] }
pimalaya-stream = { version = "0.0.1", default-features = false, optional = true }
rand = { version = "0.8", optional = true }
secrecy = { version = "0.10", default-features = false }
sha2 = { version = "0.11", optional = true, default-features = false }
thiserror = { version = "2", default-features = false }
url = { version = "2.2", default-features = false, optional = true }

# [patch.crates-io]
# pimalaya-stream.path = "../stream"

[patch.crates-io]
pimalaya-stream.git = "https://github.com/pimalaya/stream"
